//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AnimationCommandsNameSpace
{
		public enum eAnimationCommands
		{
			Play = 0,
			PlayFromFrame,
			PlayFrom,
			Stop,
			Pause,
			Resume,
			SetFrame
		}

	public struct sAnimationCommand
	{
		public tk2dSpriteAnimator m_pAnimator;
		public int m_iAnimatorIndex;
		public eAnimationCommands m_eCommand;
		public string m_sClipname;
		public int m_iFrame;
		public float m_fTime;
	}


}

